// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package registry

import (
	"github.com/integr8ly/heimdall/pkg/domain"
	"sync"
)

var (
	lockImageGetterMockGet sync.RWMutex
)

// Ensure, that ImageGetterMock does implement ImageGetter.
// If this is not the case, regenerate this file with moq.
var _ ImageGetter = &ImageGetterMock{}

// ImageGetterMock is a mock implementation of ImageGetter.
//
//     func TestSomethingThatUsesImageGetter(t *testing.T) {
//
//         // make and configure a mocked ImageGetter
//         mockedImageGetter := &ImageGetterMock{
//             GetFunc: func(in1 string) (*domain.RemoteImageDigest, error) {
// 	               panic("mock out the Get method")
//             },
//         }
//
//         // use mockedImageGetter in code that requires ImageGetter
//         // and then make assertions.
//
//     }
type ImageGetterMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(in1 string) (*domain.RemoteImageDigest, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// In1 is the in1 argument value.
			In1 string
		}
	}
}

// Get calls GetFunc.
func (mock *ImageGetterMock) Get(in1 string) (*domain.RemoteImageDigest, error) {
	if mock.GetFunc == nil {
		panic("ImageGetterMock.GetFunc: method is nil but ImageGetter.Get was just called")
	}
	callInfo := struct {
		In1 string
	}{
		In1: in1,
	}
	lockImageGetterMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockImageGetterMockGet.Unlock()
	return mock.GetFunc(in1)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedImageGetter.GetCalls())
func (mock *ImageGetterMock) GetCalls() []struct {
	In1 string
} {
	var calls []struct {
		In1 string
	}
	lockImageGetterMockGet.RLock()
	calls = mock.calls.Get
	lockImageGetterMockGet.RUnlock()
	return calls
}
